# Generated by Django 5.0.3 on 2024-03-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='enter bio text here'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='USER', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_upload/pfp'),
        ),
    ]
