# Generated by Django 5.0.3 on 2024-03-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile_bio_profile_display_name_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='{{User.username}}', max_length=300),
        ),
    ]
