# Generated by Django 5.0.3 on 2024-03-23 02:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=300),
        ),
    ]
