# Generated by Django 5.0.3 on 2024-03-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="I haven't written a bio yet!"),
        ),
    ]
