# Generated by Django 3.2.24 on 2024-02-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='tags',
            field=models.CharField(choices=[('option_one', 'untagged'), ('option_two', 'Photography'), ('option_three', 'Illustration'), ('option_four', 'Graphic Design')], default='option_one', max_length=30),
        ),
    ]
