# Generated by Django 5.0.3 on 2024-03-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userupload_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='privacy',
            field=models.CharField(choices=[('option_one', 'Public'), ('option_two', 'Private')], default='option_one', max_length=30),
        ),
    ]
