# Generated by Django 5.0.3 on 2024-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userupload_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userupload',
            old_name='image',
            new_name='image_upload',
        ),
        migrations.AddField(
            model_name='userupload',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
