# Generated by Django 5.0.3 on 2024-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_image_userupload_image_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url_upload', models.URLField()),
                ('tags', models.CharField(choices=[('option_one', 'untagged'), ('option_two', 'Photography'), ('option_three', 'Illustration'), ('option_four', 'Graphic Design')], default='option_one', max_length=30)),
                ('privacy', models.CharField(choices=[('option_one', 'Public'), ('option_two', 'Private')], default='option_one', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='userupload',
            name='image_url',
        ),
    ]
