# Generated by Django 5.0.3 on 2024-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_useruploadurl_remove_userupload_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='image_upload',
            field=models.ImageField(upload_to='user_upload/full_quality/'),
        ),
    ]
