# Generated by Django 5.0.3 on 2024-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userupload_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='image_upload_compressed',
            field=models.ImageField(default='default.jpg', upload_to='user_upload/compressed/'),
        ),
    ]
