# Generated by Django 5.0.3 on 2024-03-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userupload_image_upload_compressed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='image_upload_compressed',
        ),
        migrations.AddField(
            model_name='userupload',
            name='image_compressed',
            field=models.ImageField(blank=True, upload_to='user_upload/compressed'),
        ),
    ]
