# Generated by Django 5.0.3 on 2024-03-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
