# Generated by Django 5.0.3 on 2024-03-24 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_userupload_image_upload_compressed_and_more'),
        ('home', '0009_delete_userprofile'),
    ]

    operations = [
    ]
